### ISSUE TITLE
documentation and issues

### ISSUE THREAD

**Issue by vicentecarro** [luckyhzt/LVCD#4]
Is it possible to add some extra documentation?
In other post it was mentioned that we should run the jupyter notebook directly for inference. Assuming Jupyter is not included as part of the code (surely is not) maybe it should be mentioned as a requirement.
And "python main.py --help" output mentions lots of options that are not mentioned in the README. Do we need to create projects? What are they for?
What are the VRAM GPU requirements? would it swap to system RAM if there is not enough VRAM?

When we tried to launch the notebook it had problems reading "utils" as the first code block sets the workspace in the parent folder. 
And when tried to directly launch main without parameters, it fails with some unclear error, maybe due to the lack of parameters:
`(lvcd) vicente@vicenteGAX:/media/vicente/Samsung870VQO1TB/tests/LVCD$ python main.py
LOGDIR: logs/2024-10-17T14-06-16
Global seed set to 23
Using default TF32 settings for PyTorch 2.0.1+cu117:
torch.backends.cuda.matmul.allow_tf32=False
torch.backends.cudnn.allow_tf32=True
Traceback (most recent call last):
  File "/media/vicente/Samsung870VQO1TB/tests/LVCD/main.py", line 657, in <module>
    gpuinfo = trainer_config["devices"]
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/vicente/miniconda3/envs/lvcd/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key devices
    full_key: devices
    object_type=dict
`

And the README mentions the folder "checkpoints" for downloading the models, however that folder is not present in the git. Maybe adding a placeholder text file there could solve that. 

If you prefer I could created separated tickets for the main and the notebook issues.

**Comment by luckyhzt** [comment]
For notebook, you should set both "os.chdir()" and "sys.path.append()" to include the root directory of 'LVCD' folder. For main.py, it is only used for training, I will release the training instructions later.

**Comment by vicentecarro** [comment]
Thanks!
